### ISSUE TITLE
DXCToggle component not present in new cdk library.

### ISSUE THREAD

**Issue by ppurumala** [dxc-technology/halstack-angular#164]
We have a need where we have to show, a component on the screen like a toggle button. like: Yes/No button.
There was DXCToggle in old library-> dxc-react-cdk. We want same thing to be available in new CDK library -> halstack-react.
The Theming should also be applicable on it.

**Comment by Jialecl** [comment]
The toggle has been removed from the cdk and in the latest version you have toggle group available.

**Comment by Jialecl** [comment]
Also are you asking about react-cdk?

**Comment by peibolsang** [comment]
This is available in version 2.1.0
