### ISSUE TITLE
Wrong/Duplicate BrowserAnimationModule in DxcUploadModule imports

### ISSUE THREAD

**Issue by sahiljalan** [dxc-technology/halstack-angular#165]
Issue Reported in v1.2.7 but this module import is also present in v2.1.0

**Description**
There is wrong import of BrowserAnimationModule in DxcUploadModule. It should not be there because we already import it in app module and BrowserModule should import only once and if I import this DxcUploadModule in Lazy Module than it will throw an error due to duplicate import of BrowserAnimationModule

**To Reproduce**
1. In root AppModule import BrowserModule and BrowserAnimationModule
2. Create new Module that will be Lazyloaded and import DxcUploadModule

**Comment by SavvySparrow** [comment]
![MicrosoftTeams-image](https://user-images.githubusercontent.com/24986466/100354196-c4da0100-3015-11eb-82c1-bab0ccd92dbf.png)

**Comment by mawelCaballero** [comment]
Hello @SavvySparrow , this error has been fixed. 
Can you check it, please? 
In this case, release version will be generated and this issue will be closed.
