### ISSUE TITLE
Feature Request for Text Editor Component.

### ISSUE THREAD

**Issue by goro0710** [dxc-technology/halstack-angular#167]
Designing a message center utility where we need to **compose** Emails. For that a WYSIWYG Text Editor is required. Below is an example.

![image](https://user-images.githubusercontent.com/11742574/100422456-5e55f100-30b0-11eb-9790-a03edfe7172d.png)

As an alternative we used ngx-quill library to implement this.
https://www.npmjs.com/package/ngx-quill

**Comment by mawelCaballero** [comment]
Hello @goro0710 , 
thanks about the proposition about including a rich text editor in our cdk but unfortunately it is not included in the design style repo. The way to make a request is open an issue/request in this **[repository](https://github.com/dxc-technology/halstack-style-guide)** and it will be discussed to be included as **cdk component** in both technologies (react and angular) following a route map. 
Thanks.
