### ISSUE TITLE
Select and Date Component Style Issue

### ISSUE THREAD

**Issue by SavvySparrow** [dxc-technology/halstack-angular#168]
Reported version v2.1.0

Select Component label and undeline color is at 42 to 54% opacity of black and we dont have control of it. like it mentioned I have imported default material styles > ./node_modules/@angular/material/prebuilt-themes/indigo-pink.css.

**Select Component** only support this style token -> `selectedOptionBackgroundColor`
**Date Component** only support these style token -> `pickerSelectedDateBackgroundColor & pickerSelectedDateColor`

There is no way to create dark version of select and date component using theme API. I do need to manualy override those.
Just like Input field we do need seperate fontColor field for select and date. Right now for a time being we are overriding select font color using --inputText-fontColor token.

**Expected Token Example**

**Select component style -> we do need select-font-color**
`.mat-form-field-appearance-legacy .mat-form-field-label {
  color: var(--select-fontColor);
}`
`.mat-form-field-appearance-legacy .mat-form-field-underline {
  background-color: var(--select-fontColor);
}`
`.mat-select-arrow {
  color: var(--select-fontColor);
}`

**Image showing Select Component styles without override**

![image](https://user-images.githubusercontent.com/24986466/100427864-1b4c4b80-30b9-11eb-84c1-6a701fb88296.png)

If you see it looks odd when compare to input field.

**Comment by SavvySparrow** [comment]
**Correction**
Please correct me, I think Date component will be fine because internally it is using dxc-input. so if i do change --inputText-fontColor token it will reflect on Date component also

**Comment by Lisa159** [comment]
Hi,
Yes, some components are related between them. In this case dxc-date is consuming dxc-input. In regards of the token, we will discuss it internally, this is a design change, not a bug. 
Please, take a look at this repository: https://github.com/dxc-technology/halstack-style-guide
You can open design issues there.
Regards.

**Comment by SavvySparrow** [comment]
Sure. I will create there. thanks for the quick response. @Lisa159
