### ISSUE TITLE
Select component label and arrow colors are not as per standard style guidlines

### ISSUE THREAD

**Issue by sahiljalan** [dxc-technology/halstack-angular#169]
As per [Select Style guildline](https://developer.dxc.com/design/components/select) the default label and underline color is #000000

Please check below states of this field

![image](https://user-images.githubusercontent.com/24986466/100440605-2c9e5380-30cb-11eb-950e-16a8efa61ab6.png)

If you see the `normal` and `select with focus` state above it is clealy visible that only difference is in underline color which is not pitch black in normal state. The down arrow and label both remains #000000
Another state is `select clicked` where If you see the first options is not highlighted. It will only hightlight if user hover it.

Now compare above cases with [current select implementation(https://developer.dxc.com/tools/angular/2/#/components/select)](https://developer.dxc.com/tools/angular/2/#/components/select) where label and arrow color is not black #000000 in `normal state` and first selection is auto highlighted in `select clicked` state without hover it.

![image](https://user-images.githubusercontent.com/24986466/100441509-99feb400-30cc-11eb-85ec-c80ead4efc39.png)
![image](https://user-images.githubusercontent.com/24986466/100441724-f06bf280-30cc-11eb-9d8f-f77d250ed44e.png)

Please correct if there are any other  [Style guildlines](https://developer.dxc.com/design/components)

Regarding token visibility of label and underline, I have created issue in [halstack-style-guide](https://github.com/dxc-technology/halstack-style-guide/issues/10)

@Lisa159 @mawelCaballero

**Comment by Jialecl** [comment]
Thanks @SavvySparrow for reporting the issue the fix has been merged.
It is already available so please check if everything is correct.
