### ISSUE TITLE
Resultsettable  pagination and sorting functionality is not working.

### ISSUE THREAD

**Issue by karumalla** [dxc-technology/halstack-angular#193]
**Describe the bug**
 After configuring the Resuresultsettable  The pagination and sorting functionality is not working 
I am using the below version of   halstack-angular,
"@dxc-technology/halstack-angular": "2.1.0",
**To Reproduce**
Configure the Result set table. 

In the console, i am getting the below error, for reference I am attaching the screen prints below.
![image](https://user-images.githubusercontent.com/76098620/102332172-bf872b00-3fb1-11eb-9e8e-b1365a9ee6d8.png)

**Comment by mawelCaballero** [comment]
Solved in next versions but waiting for new release.

**Comment by mawelCaballero** [comment]
It has been solved in new release version: 3.0.0
