### ISSUE TITLE
URL to 'document site' 404's

### ISSUE THREAD

**Issue by jeremiah** [dxc-technology/halstack-angular#20]
**Describe the bug**
URL to 'document site' 404's

**To Reproduce**
1. surf to [halstack-angular README.md](https://github.com/dxc-technology/halstack-angular)
2. Click on "document site" under the "usage" section

**Expected behavior**
Working URL

**Screenshots**
N/A

**Add labels**
Add any applicable label like the concerned components or the target version of the **fwk** where the bug has been found.
(What is fwk?)

**Comment by mawelCaballero** [comment]
Thanks @jeremiah, that issue is fixed now.

There could still exist some other issues like that one, since we are still finishing up with the transition from our private repositories and npm registries. Hopefully we'll have it all set by the end of this week.
