### ISSUE TITLE
ExpressionChangedAfterItHasBeenCheckedError in Tab Component

### ISSUE THREAD

**Issue by Lisa159** [dxc-technology/halstack-angular#248]
**Describe the bug**
There is an ExpressionChangedAfterItHasBeenCheckedError when using prop iconSrc in a tab component.

**To Reproduce**
1. Use dxc-tabs component.
1. Add prop iconSrc in one tab.
2. Open inspector.
3. See error.

**Expected behavior**
It should not appear any error.

**Screenshots**
![image](https://user-images.githubusercontent.com/34685461/104917872-473acd80-5994-11eb-8f31-64cba8af4ae9.png)
![image](https://user-images.githubusercontent.com/34685461/104917888-4efa7200-5994-11eb-9e31-7a7be307919f.png)

**Comment by mawelCaballero** [comment]
It has been solved in new release version: 3.0.0
