### ISSUE TITLE
'Result set table' component throwing error. Not able to setup the 'halstack-angular' project. 

### ISSUE THREAD

**Issue by Kathirvel-DXC** [dxc-technology/halstack-angular#264]
**Describe the bug**
I've tried to configure dxc halstack-angular in my localhost as per the guidelines from 'https://developer.dxc.com/tools/angular/2/#/overview'. I'm getting the below error from "Result set table", for reference I am attaching the screen prints below. I'm using the below version of halstack-angular,
"@dxc-technology/halstack-angular": "2.1.0",
Dependencies:
"@angular-devkit/build-angular": "~0.1100.7",
"@angular/cli": "~11.0.7",
"@angular/compiler-cli": "~11.0.9",

**To Reproduce**
1. Start a new empty Angular project
2. Install the 'halstack-angular' dependencies(As per the guidelines from 'https://developer.dxc.com/tools/angular/2/#/overview'
3. Run the app

**Screenshots**
![image](https://user-images.githubusercontent.com/78808862/107386131-90a4b580-6b19-11eb-88b9-1827b5f1d700.png)
![image](https://user-images.githubusercontent.com/78808862/107386153-96020000-6b19-11eb-9f7a-b21e6e643253.png)

**Comment by mawelCaballero** [comment]
CDK is not supporting angular 11. 
It will be supported in nex release versions so far, it has been defined with angular 10 version.
