### ISSUE TITLE
Header logo static icon is not correct in the component

### ISSUE THREAD

**Issue by Tarun-DXC** [dxc-technology/halstack-angular#295]
**Describe the bug**
DXC logo static icons - "dxc_logo_white.png" and "dxc_logo_white.png" are not correct 

**To Reproduce**
Use halstack angular library and define dxc-header component. Incorrect logo comes

Example:
https://developer.dxc.com/tools/angular/2/#/components/header

**Expected behavior**
Header icon should be correct per the guideline

**Screenshots**
![image](https://user-images.githubusercontent.com/80850088/111519182-d427ba80-877c-11eb-9637-b7f524cdc479.png)

**Additional context**

**Add labels**
Add any applicable label like the concerned components or the target version of the fwk where the bug has been found.

**Comment by peibolsang** [comment]
@mawelCaballero please look into this issue

**Comment by mawelCaballero** [comment]
It has been fixed in release 3.0.0 
Issue can be closed.
