### ISSUE TITLE
Breaking changes in dxc sidenav component

### ISSUE THREAD

**Issue by Tarun-DXC** [dxc-technology/halstack-angular#322]
**Describe the bug**
1. arrow that allows the user to hide or show the component on the screen not supported in 3.0.0
2. Modes push and overlay no more supported

**To Reproduce**
https://codesandbox.io/s/sidenavwithchildren-forked-bcjt6?file=/src/app/app.component.html

**Expected behavior**
Sidenav should support arrow and modes as mentioned in guideline

**Screenshots**

**Additional context**
There are 2 sidenavs in cdk. One on application-layout component and another standalone sidenav. Both have different APIs. In my opinion a sidenav is a sidenav irrespective of implementation and application-layout should use standalone sidenav component.

**Comment by Tarun-DXC** [comment]
@mawelCaballero - This fix you made is for app-layout. The issue I have opened is for dxc-sidenav component.
In my opinion this issue needs to be reopened

cc: @peibolsang

**Comment by mawelCaballero** [comment]
Due to inactivity this issue is closed.
