### ISSUE TITLE
Path of font files incorrect in fonts.scss

### ISSUE THREAD

**Issue by Tarun-DXC** [dxc-technology/halstack-angular#323]
**Describe the bug**
When I include theme.scss in angular json under styles, it throws error for incorrect path of font files. It is because /lib is not included in the path

**To Reproduce**
Create a project with halstack-angular as dependency and include theme.scss as external styles in angular.json

**Expected behavior**
theme.scss should be added without build errors

**Screenshots**
![image](https://user-images.githubusercontent.com/80850088/115153040-819a3080-a091-11eb-80d3-0414a254ce2b.png)

**Comment by mawelCaballero** [comment]
Hello @Tarun-DXC  
It has been fixed in https://github.com/dxc-technology/halstack-angular/issues/319#issue-857013752
It's available on next version. It will be included in a new release version during these days.

**Comment by sponnuswamydxc** [comment]
@mawelCaballero , Did you mean 3.0.1 as the next version ?

**Comment by mawelCaballero** [comment]
Sure @sponnuswamydxc , before of the end of week we'll publish a 3.0.1 version.

**Comment by Tarun-DXC** [comment]
@mawelCaballero Still waiting for 3.0.1 version to pull in this fix. Can you please publish at the earliest

cc: @peibolsang , @sponnuswamydxc

**Comment by mawelCaballero** [comment]
Hi @Tarun-DXC , Angular cdk 3.0.1 has been released. 
https://github.com/dxc-technology/halstack-angular/releases/tag/3.0.1
