### ISSUE TITLE
[Sidenav] Angular components

### ISSUE THREAD

**Issue by GauravMaurya0** [dxc-technology/halstack-angular#335]
Padding should be 48 px, Arrow should be visible with 50% value

![Picture2](https://user-images.githubusercontent.com/75359999/115825093-90cd0580-a426-11eb-98ab-f6ea77df29df.png)

**Comment by Lisa159** [comment]
Hi,

The sidenav example has a padding prop with value "medium". Checking the guidelines I can see that the value for "medium" is 36px and for "large" is 48px.

![image](https://user-images.githubusercontent.com/34685461/120348739-bf7bad00-c2fd-11eb-9cce-6c09b9974602.png)

**Comment by aweell** [comment]
I close the issue, the documentation was updated on May 6th to cover all the possible values the `margin` property can take.
