### ISSUE TITLE
Sized Button mode prop

### ISSUE THREAD

**Issue by mnnaveenk** [dxc-technology/halstack-angular#336]
Sized button Example:

```
<div theme>
  <dxc-button
    mode="secondary"
    label="Basic Button"
    (onClick)="onClick()"
    margin="medium"
    mode="primary"
    size="large"
  ></dxc-button>
</div>
```

The mode is Property is repeating which can be removed.

Icon Size [**design specs**]: not shown in the table

**Comment by Lisa159** [comment]
Repeated mode prop has been removed from the example. Closing issue.
