### ISSUE TITLE
[Tabs] - Component specs

### ISSUE THREAD

**Issue by mnnaveenk** [dxc-technology/halstack-angular#337]
Design Specification Table is missing.
Not enough of examples of header variants as compared to the images in the documentation.

icon color [**image**] = #6F2C91
icon color [**implementation**] = black

padding left in tab label after the icon [**image**] = 12px
padding left in tab label after the icon [**implementation**] = 0px

padding top in tab label above the icon [**image**] = 8px
padding top in tab label above the icon [**implementation**] = 0px

font in tab label [**implementation**] = Roboto, "Helvetica Neue"
font in tab label [**image**] = 'open sans semi bold'

Fixed Tab height [**implementation**] = 46px
Fixed Tab height [**image**] = 48px

scrollable tabs = no specs
tabs with notifications = no specs

**Comment by mawelCaballero** [comment]
It has been fixed, It will be available in the next release.
