### ISSUE TITLE
Dropdown : when the dropdown have more values, the scroll bar appears. But, we are unable to scroll and select the lower most values.

### ISSUE THREAD

**Issue by babdullah-at-dxc-dot-com** [dxc-technology/halstack-angular#339]
**Describe the bug**
Dropdown : when the dropdown have more values, the scroll bar appears. But, we are unable to scroll and select the lower most values. Most likely the scroll bar is very thin and very difficult to use mouse scroll down to see the bottom most values.

Also, when i select the control and use up/down arrow keys, it did not navigate the items in the list.

**Comment by mawelCaballero** [comment]
This fix has been included in the release 3.0.2
https://www.npmjs.com/package/@dxc-technology/halstack-angular/v/3.0.2

The width of the scroll bar has been defined in the guidelines.

**Comment by Kanhaya-DXC** [comment]
Hi @mawelCaballero To replicate the fixes we are using "@dxc-technology/halstack-angular": "next" version, Using mouse and keyboard we are able to scroll and select but using dropdown scrollbar which appearing in right side we are unable 
to do that. please refer below screenshot.
![bbb](https://user-images.githubusercontent.com/85492869/121010658-4ffd3600-c7b3-11eb-9724-21a54f9b7882.jpg)

**Comment by Jialecl** [comment]
Hi @Kanhaya-DXC,  if we understand you correctly you are not able to move dragging the scrollbar.
But we are not ablo to reproduce the issue. 
Can you try it on this codesandbox?
https://codesandbox.io/s/defaultdropdown-bvpz4?file=/src/app/app.component.html

**Comment by jsardid** [comment]
@Jialecl in that codesandbox I'm able to reproduce what @Kanhaya-DXC is saying. 

BUT I don't think that's an issue. In this component I think that bar is just a visual cue of the scroll position, and not something to be dragged. @aalbuerne am I right?

**Comment by mchaudhary5** [comment]
Please review the issue once more, resolution is required so that user can clearly see there are more items in dropdown and scroll down to see all input values.
