### ISSUE TITLE
Dropdown : OnSelectOption not working.

### ISSUE THREAD

**Issue by babdullah-at-dxc-dot-com** [dxc-technology/halstack-angular#340]
**Describe the bug**
Dropdown : OnSelectOption not working.

Refer the app.component.html and app.component.ts in https://developer.dxc.com/tools/angular/3/#/components/dropdown

**Comment by mawelCaballero** [comment]
Hello @babdullah-at-dxc-dot-com , There was a problem with onSelectOption in the examples but it's already fixed. 
Please, check it.

**Comment by mawelCaballero** [comment]
Being more specific, the error was defining the (onSelectOption)="selected($event)" in dxc-dropdown-option instead of dxc-dropdown.

### Before

<dxc-dropdown
    label="Default Dropdown"
    size="medium"
    expandOnHover="true"
    margin="small">
    <dxc-dropdown-option label="Facebook" value="1" (onSelectOption)="selected($event)">
      Facebook
    </dxc-dropdown-option>
    <dxc-dropdown-option label="Twitter"> </dxc-dropdown-option>
    <dxc-dropdown-option label="Linkedin"> </dxc-dropdown-option>
  </dxc-dropdown>

### After

<dxc-dropdown
    label="Default Dropdown"
    size="medium"
    expandOnHover="true"
   (onSelectOption)="selected($event)"
    margin="small">
    <dxc-dropdown-option label="Facebook" value="1" >
      Facebook
    </dxc-dropdown-option>
    <dxc-dropdown-option label="Twitter"> </dxc-dropdown-option>
    <dxc-dropdown-option label="Linkedin"> </dxc-dropdown-option>
  </dxc-dropdown>
