### ISSUE TITLE
Select component Font size is not reducing when the label contains a long text.

### ISSUE THREAD

**Issue by babdullah-at-dxc-dot-com** [dxc-technology/halstack-angular#347]
Select component Font size is not reducing when the label contains a long text.

If the Select components label contains a long text , the font is not reduced, thus the text overflows into the select dropdown control. It works well when i add multiselect property. Refer the attached screen shots for the differences.

![Select_OverlappedText_2](https://user-images.githubusercontent.com/83747111/117675951-b306a780-b1ca-11eb-910f-dd4545ea8a45.jpg)
![Select_OverlappedText_1](https://user-images.githubusercontent.com/83747111/117675958-b4d06b00-b1ca-11eb-95f1-27da591e2049.jpg)

**Comment by mawelCaballero** [comment]
This fix has been included in the release 3.0.2
https://www.npmjs.com/package/@dxc-technology/halstack-angular/v/3.0.2

**Comment by Kanhaya-DXC** [comment]
Hi @mawelCaballero  To replicate the fixes we are using "@dxc-technology/halstack-angular": "next" version, For this issue we are unable to the fixes, still getting same issue. please refer below screenshot.
![aa](https://user-images.githubusercontent.com/85492869/121010428-06ace680-c7b3-11eb-9567-9fad4b8c4354.jpg)

**Comment by Jialecl** [comment]
Hello @Kanhaya-DXC ,
We are not able to reproduce the issue using the "next" version.
This is a codesandbox with a similar scenario:
https://codesandbox.io/s/required-select-c3qcq?file=/src/app/app.component.css

**Comment by jsardid** [comment]
@Jialecl, is it also fixed in 3.0.2? Manu is saying it's there already.

**Comment by Jialecl** [comment]
@jsardid  yes, the version 3.0.2 includes the fix regarding the select label.
