### ISSUE TITLE
Textarea

### ISSUE THREAD

**Issue by mnnaveenk** [dxc-technology/halstack-angular#348]
**No documentation specs available**
---------

**Controlled Textarea**

[**react**]- the example is not working in comparison with the Angular example. [there is 5 character input restriction in angular but there is no restriction in react example]

[**Angular**] - 'Sized Slider' example is added in the textarea examples list which can be removed

**Comment by mawelCaballero** [comment]
This fix has been included in the release 3.0.2
https://www.npmjs.com/package/@dxc-technology/halstack-angular/v/3.0.2

About the difference between angular and react cdk's in the examples. It has not been the same. 
The example about the controlled component is just what it its. It's an example which demonstrates how ngModel value can be controlled by the programmer.
