### ISSUE TITLE
[Select] Component specs

### ISSUE THREAD

**Issue by aweell** [dxc-technology/halstack-angular#351]
Default Select

in  Image
![image](https://user-images.githubusercontent.com/83015051/117485468-05a35200-af86-11eb-9a95-d7af1347e621.png)

As per Multi select Implementation
![image](https://user-images.githubusercontent.com/83015051/117485542-1784f500-af86-11eb-854c-53083e8ef6e9.png)
--------------
Font in the select dropdown is using 'Roboto font'
![image](https://user-images.githubusercontent.com/83015051/117486423-3f288d00-af87-11eb-9ea7-177f63ac6e52.png)
--------------

Select on focus in implementation is
select-focusColor: #005FCC;
![image](https://user-images.githubusercontent.com/83015051/117755394-bedd8280-b239-11eb-8c83-17a44259f13e.png)

Select on focus by guidelines:
![image](https://user-images.githubusercontent.com/44420072/119560679-8050d780-bda4-11eb-9a5a-19c577334f0f.png)

---------------

In all the Angular Implementation examples when any interaction is done on the select component the arrow is not interactive, it does not rotate according to action. pointing  up words in normal state when dropdown is enabled the arrow should point up, but as of now it always points down as shown in the image below.
![image](https://user-images.githubusercontent.com/83015051/117760834-f7825980-b243-11eb-8f3f-38f25d5e516a.png)

**Comment by aweell** [comment]
The checkbox shouldn't display the focus state:

![Captura de pantalla 2021-05-26 a las 9 48 26](https://user-images.githubusercontent.com/44420072/119622673-a8bded80-be07-11eb-88ac-e180d5ee9ac5.png)

https://github.com/dxc-technology/halstack-react/issues/312#issue-901265301

**Comment by mawelCaballero** [comment]
@Jialecl  Can you talk with @aweell about this issue?
