### ISSUE TITLE
Accordion assistive text

### ISSUE THREAD

**Issue by Lisa159** [dxc-technology/halstack-angular#355]
Size of an assistive text inside an accordion

Try to prevent line-breaks in the main label "the title of the accordion" when the assistive text is long or space available is limited (Panels, mobile devices...)

![image](https://user-images.githubusercontent.com/34685461/120213944-1b79ff00-c234-11eb-9483-64d77fb58eb3.png)

Preliminary Solution
Limit the maximum of characters that an assistive text can have.

**Comment by mawelCaballero** [comment]
There's a new release version and this fix has been include it. 
https://www.npmjs.com/package/@dxc-technology/halstack-angular/v/3.0.2
