### ISSUE TITLE
[Button] Documentation update

### ISSUE THREAD

**Issue by aweell** [dxc-technology/halstack-angular#364]
Update of the button guidelines is available [here](https://developer.dxc.com/design/guidelines/components/button).

**Changes coming with the update:**

- [x] Secondary `border-width` changes from 2px to 1px, focus state remains as 2px.
- [x] Height of the component is reduced from 43px to 40px
- [x] Removal of `text-transform: uppercase` property
- [x] Increase in the `font-size` from 14px to 16px
- [x] Spacing between icon and label is 8px
- [x] Reduced `padding-left` and `padding-right` from 30px to 24px

**Comment by Lisa159** [comment]
Changes implemented in the branch advance-theme. They will be available in the next release. Closing issue.
