### ISSUE TITLE
Dynamic rendering of Tabs is not working    

### ISSUE THREAD

**Issue by apallamreddy** [dxc-technology/halstack-angular#365]
**Describe the bug**
we are displaying the tabs when user option it(button click )  we are updating array with new value(array size will  increase) for the first time tab loop is rendering immediately and tab is displaying immediately in uI side

when user option for second time(button click)  we are updating array with new values(array size will  increase)  but the tab(loop) is not rendering in uI side when array is updated also with new values (array length increase ) when we click 3th time or on clicking first tab the new lee added tab is displaying
    
**Expected behavior**
the loop should render immediately when array is  updated and new lee add tab should display 
**Screenshots**
I have attached the screen of the code we have implemented   
![Screenshot (128)](https://user-images.githubusercontent.com/85341742/120783008-3ad09f00-c548-11eb-924d-f5d40d8c4f68.png)
![Screenshot (129)](https://user-images.githubusercontent.com/85341742/120783016-3d32f900-c548-11eb-8a7e-fd93acb203c5.png)

**Additional context**

**Add labels**
Add any applicable label like the concerned components or the target version of the fwk where the bug has been found.

**Comment by Kanhaya-DXC** [comment]
Actually this is Tab UI component related issue and it required in our application urgently and because of it we are stuck so may i know any update about this issue?

**Comment by mawelCaballero** [comment]
We are working on that. we will fix it ASAP

**Comment by mawelCaballero** [comment]
Hello @Kanhaya-DXC , the add tabs dynamically feature has been added to tabs component. 
Check the example in halstack-angular site or access directly to 
https://codesandbox.io/s/addtabsdynamically-n1fcj?fontsize=14&hidenavigation=1&module=%2Fsrc%2Fapp%2Fapp.component.html&theme=dark 

This feature is currently in latest (next) version. It will be included in the next release.

**Comment by mchaudhary5** [comment]
Please provide date by when next release will be available which includes this fix.

**Comment by mawelCaballero** [comment]
This is available in 3.0.3.

**Comment by apallamreddy** [comment]
Hi @mawelCaballero ,
We have updated the Version to 3.0.4 and try to implement the dynamic tabs rendering as it is in cdk component we are unable to implement  we are  getting straight line that all i have attached the screen of code we have implement
![Screenshot (195)](https://user-images.githubusercontent.com/85341742/122916259-52968880-d37a-11eb-888a-fca02ede2b19.png)
![Screenshot (196)](https://user-images.githubusercontent.com/85341742/122916267-54604c00-d37a-11eb-8da1-9a77384d33ee.png)
![Screenshot (197)](https://user-images.githubusercontent.com/85341742/122916268-54f8e280-d37a-11eb-83c1-4f1cbad5b254.png)
![Screenshot (198)](https://user-images.githubusercontent.com/85341742/122916270-55917900-d37a-11eb-8e4e-3a2254f85050.png)
![Screenshot (199)](https://user-images.githubusercontent.com/85341742/122916276-55917900-d37a-11eb-87e8-ea6b5b243706.png)

**Comment by mawelCaballero** [comment]
This is the same example in codesandbox using latest release version of halstack-angular. 
https://codesandbox.io/s/addtabsdynamically-n1fcj?fontsize=14&hidenavigation=1&module=/src/app/app.component.html&theme=dark&file=/src/app/app.component.ts
And its working as expected.

**Comment by mawelCaballero** [comment]
In case of updating to the latest version previously commented  and still is not working. Can you share with us a repository and we can have a look at this?
Thanks in advance.

**Comment by apallamreddy** [comment]
Hi @mawelCaballero ,
we created one test env to replicate this issue You can clones  the development branch  from below git repo ones done run npm install and ones done run ng serve ones application open you can see the issue it showing only straight line. Not any tabs

https://github.dxc.com/apallamreddy/diaas-web-starter/tree/development

**Comment by mawelCaballero** [comment]
I have had a look at your source code and there is no problem related to the "dxc-tabs" component.
In the examples on the dxc-halstack angular website there is a subtle difference and that is that the dxc-tabs component only contains dxc-tab components. 

Your code: 

<div theme>
    <dxc-tabs margin="small">
        <div >
            <dxc-tab [label]="currenttab.id" *ngFor="let currenttab of (tabs | async); let i = index;">
                <div id="content1">{{currenttab.content}}</div>
            </dxc-tab>
        </div>
    </dxc-tabs>
    <dxc-button label="Add new tab" (click)="addMoreTabs()"></dxc-button>
</div>

How it has to be: 
<div theme>
    <dxc-tabs margin="small">
            <dxc-tab [label]="currenttab.id" *ngFor="let currenttab of (tabs | async); let i = index;">
                <div id="content1">{{currenttab.content}}</div>
            </dxc-tab>
    </dxc-tabs>
    <dxc-button label="Add new tab" (click)="addMoreTabs()"></dxc-button>
</div>

**Comment by apallamreddy** [comment]
Hi @mawelCaballero ,
Thank for update it working now

**Comment by mawelCaballero** [comment]
Welcome :)
