### ISSUE TITLE
Border is displaying  around date picker icon after closing the calendar  & calendar is not closing on click on icon ones opend 

### ISSUE THREAD

**Issue by apallamreddy** [dxc-technology/halstack-angular#366]
**Describe the bug**
1)please open the calendar on clicking calendar icon and select any date you can see the border around the icon which is displaying  
2) open the calendar on clicking date picker icon again click on  same icon calendar is still showing not closing   
**Expected behavior**
The border should not be show around the icon ones calendar is closed or date is selected  for time it self
on clicking  date picker icon  the calendar should close 
**Screenshots**
![Screenshot (134)](https://user-images.githubusercontent.com/85341742/121017103-84282500-c7ba-11eb-9ae0-631ddeccbe08.png)
![Screenshot (136)](https://user-images.githubusercontent.com/85341742/121017115-85f1e880-c7ba-11eb-935c-436efdc1f0b1.png)

**Comment by mchaudhary5** [comment]
Please provide ETC for this issue.

**Comment by jsardid** [comment]
Is the issue with the border itself? Or with the calendar keeping the focus after having picked a date? I think I don't fully understand where exactly is the issue here.

**Comment by apallamreddy** [comment]
Hi @jsardid ,
1)The calendar is keeping focus after picking date.
2)on  calendar  is open when I re click the calendar icon  opened  Calendar is not closing

**Comment by aweell** [comment]
Hi @apallamreddy 

When a value from the date dialog is selected the focus moves back to the trigger, that's a common behavior. You can check the related behavior in the [WAI-ARIA date picker dialog example](https://www.w3.org/TR/wai-aria-practices/examples/dialog-modal/datepicker-dialog.html).

**Keyboard interaction from the dialog example documentation**

> Key | Function
> -- | --
> Enter, space | Select the date, close the dialog, and move focus to the&nbsp;Choose Date&nbsp;button.
>
