### ISSUE TITLE
UI Configurator tool to customize screens developed using CDK

### ISSUE THREAD

**Issue by Tarun-DXC** [dxc-technology/halstack-angular#374]
**Is your feature request related to a problem? Please describe.**
CDK does not provide any UI Configuration tools to customize fields on a screen except theming. In P&C Americas, UI screens are highly customized by Carriers based on their business. 
Lack of capability to customize UI screens and workflows by rearranging and grouping of fields by a Business User is a big gap in the product offering in Assure SOE and a deterrent for future sales

**Describe the solution you'd like**
A tool that can be used by a Business User to configure the screens developed using CDK. User should be able to add/remove fields from the screen, rearrange fields on the screen, create new sections. Once he/she saves their changes, the UI rendering engine should display the updated screen. This is similar to UX configurator present in UI FWK 2.0

**Describe alternatives you've considered**
None

**Additional context**
UX Configurator tool from UI FWK 2 had this capability

**Add Labels**
screen-customization

**Comment by peibolsang** [comment]
The Design System is a tool for designers and developer, not for business users. This is not a feature we will incorporate in our dev tooling, again, for Business Users
