### ISSUE TITLE
[Dropdown] Component specs

### ISSUE THREAD

**Issue by aweell** [dxc-technology/halstack-angular#376]
## Updated dropdown component specs

[Component guidelines](https://developer.dxc.com/design/guidelines/components/dropdown) released in 3.2.0

![ ]( https://s3.amazonaws.com/design.system.components.catalog/guidelines/components/dropdown/images/dropdown_states.png )

- [x] Update component `hover`, `focus` and `active` states.
- [x] Add `disabled` state

|  State     |  Value          |
| -------- | -----------  |
| `hover`  |  #F2F2F2    |
| `focus`  |  #0067B3   |
| `active` |  #D9D9D9  |

![ ]( https://s3.amazonaws.com/design.system.components.catalog/guidelines/components/dropdown/images/dropdown_specs.png )

- [x] Update dropdown button `padding` properties
- [x] Update options list specs and states

**Comment by Lisa159** [comment]
Changes implemented in the branch advance-theme. They will be available in the next release. Closing issue.
