### ISSUE TITLE
[Autocomplete] Component specs

### ISSUE THREAD

**Issue by aweell** [dxc-technology/halstack-angular#378]
## Updated autocomplete component specs

[Component guidelines](https://developer.dxc.com/design/guidelines/components/autocomplete) released in 3.2.0

![](https://s3.amazonaws.com/design.system.components.catalog/guidelines/components/autocomplete/images/autocomplete_specs.png)

- [x] Update options list states and specs following the [dropdown documentation](https://developer.dxc.com/design/guidelines/components/dropdown).

**Comment by Lisa159** [comment]
Changes implemented in the branch advance-theme. They will be available in the next release. Closing issue.
