### ISSUE TITLE
[Date] Component specs

### ISSUE THREAD

**Issue by aweell** [dxc-technology/halstack-angular#379]
## Updated date-picker component specs

[Component guidelines](https://developer.dxc.com/design/guidelines/components/date) released in 3.2.0

![](https://s3.amazonaws.com/design.system.components.catalog/guidelines/components/date/images/date_states.png)

- [x] Fix focus state on suffix.

Property  |  element | value
--------- | ---------- | ----------
`border-color` | focus outline | #0067b3
`border-width` | focus outline | 2px

![](https://s3.amazonaws.com/design.system.components.catalog/guidelines/components/date/images/date_popup.png)

- [x] Update calendar dialog element states: `focus`, `selected`(active)

**Comment by Lisa159** [comment]
Changes implemented in the branch advance-theme. They will be available in the next release. Closing issue.
