### ISSUE TITLE
When label size is big  in the select  component remaining label is not showing  instead of it showing ...when screen is inany resolution

### ISSUE THREAD

**Issue by apallamreddy** [dxc-technology/halstack-angular#384]
**Describe the bug**
when we provide large label in select component it is not showing remining label instead of it showing ...  when screen is in any resolution
**To Reproduce**
1) take div size col-4 and implement select component 
2) provide large label for the select field you can see entire label is not showing remining label is hiding instead of it showing ...
3) when screen is in  any resolution
Example:
**Expected behavior**
entire label should show to user in next line with out over lapping to bottom line when the screen in any resulation
 
**Screenshots**
![Screenshot (186)](https://user-images.githubusercontent.com/85341742/122725646-d83f0900-d292-11eb-846a-135f660b7167.png)
![Screenshot (187)](https://user-images.githubusercontent.com/85341742/122725660-daa16300-d292-11eb-84e6-c4158567c0a2.png)

**Comment by Jialecl** [comment]
Hello @apallamreddy ,

This is working as intended.
I would suggest using size="fillParent" if you are defining the width in the parent element.

**Comment by apallamreddy** [comment]
Hi @Jialecl ,
we are using size="fillParent" only but div size is col-3 when my screen resolution is 100% i can not see entire label 
![Screenshot (189)_LI](https://user-images.githubusercontent.com/85341742/122735479-b34f9380-d29c-11eb-8a66-fbd0c687c20f.jpg)
![Screenshot (190)](https://user-images.githubusercontent.com/85341742/122735491-b5b1ed80-d29c-11eb-8b2e-987a17c40d3a.png)

**Comment by jsardid** [comment]
Hi, I don't see how this is a CDK issue. We cannot just accommodate any label with any length, and we are forced to truncate it. This happens because you are not allocating enough space for the input.

You can either allocate more space or use a shorter label.
