### ISSUE TITLE
[Tokens] Updated tokens

### ISSUE THREAD

**Issue by aweell** [dxc-technology/halstack-angular#406]
// Color
  
  inherit: "inherit",
  transparent: "transparent",

  hal_white: "#ffffff",
  hal_grey_l_95: "#f2f2f2",
  hal_grey_l_90: "#e6e6e6",
  hal_grey_l_80: "#cccccc",
  hal_grey_l_75: "#bfbfbf",
  hal_grey_l_60: "#999999",
  hal_grey_s_40: "#666666",
  hal_black: "#000000",
  
  hal_purple_l_95: "#f2eafa",
  hal_purple_l_90: "#e5d5f6",
  hal_purple_l_65: "#a46ede",
  hal_purple_s_38: "#5f249f",
  hal_purple_d_30: "#4b1c7d",
  hal_purple_d_20: "#321353",
  
  hal_blue_l_95: "#e6f4ff",
  hal_blue_l_80: "#99d5ff",
  hal_blue_l_50: "#0095ff",
  hal_blue_l_45: "#0086e6",
  hal_blue_s_35: "#0067b3",
  hal_blue_d_20: "#003c66",
  
  hal_red_l_95: "#ffe6e9",
  hal_red_l_80: "#fe9aa7",
  hal_red_l_60: "#fe344f",
  hal_red_s_41: "#d0011b",
  hal_red_d_30: "#980115",
  hal_red_d_20: "#65010e",
  
  hal_green_l_95: "#eafaef",
  hal_green_l_80: "#acecbe",
  hal_green_s_39: "#24a148",
  hal_green_d_30: "#1c7d38",
  hal_green_d_20: "#135325",
  
  hal_yellow_l_95: "#fef9e6",
  hal_yellow_l_80: "#fbe89d",
  hal_yellow_s_57: "#f7cf2b",
  hal_yellow_d_40: "#c59f07",
  hal_yellow_d_30: "#947705",
  
  hal_orange_s_54: "#f38f20",
  
  // Typography
  
  type_sans: "Open Sans, sans-serif",
  
  type_scale_root: "16px",
  type_scale_08: "3.75rem",
  type_scale_07: "3rem",
  type_scale_06: "2rem",
  type_scale_05: "1.5rem",
  type_scale_04: "1.25rem",
  type_scale_03: "1rem",
  type_scale_02: "0.875rem",
  type_scale_01: "0.75rem",
  
  type_light: "300",
  type_regular: "400",
  type_semibold: "600",
  
  type_bold: "bold",
  type_italic: "italic",
  type_normal: "normal",
  
  type_spacing_tight_02: "-0.05em",
  type_spacing_tight_01: "-0.025em",
  type_spacing_normal: "0",
  type_spacing_wide_01: "0.025em",
  type_spacing_wide_02: "0.05em",
  type_spacing_wide_03: "0.1em",
  
  type_initial: "initial",
  type_uppercase: "uppercase",
  type_no_line: "none",
  type_underline: "underline",
  type_line_through: "line-through",
  
  type_leading_compact_03: "1em",
  type_leading_compact_02: "1.25em",
  type_leading_compact_01: "1.365em",
  type_leading_normal: "1.5em",
  type_leading_loose_01: "1.75em",
  type_leading_loose_02: "2em",
  
  // Spacing
  
  spacing_00: "0rem",
  spacing_01: "0.125rem",
  spacing_02: "0.25rem",
  spacing_03: "0.5rem",
  spacing_04: "0.75rem",
  spacing_05: "1rem",
  spacing_06: "1.5rem",
  spacing_07: "2rem",
  spacing_08: "2.5rem",
  spacing_09: "3rem",
  spacing_10: "3.5rem",
  spacing_11: "4rem",
  spacing_12: "5rem",
  spacing_13: "6rem",
  spacing_14: "7rem",
  
  // Border
  
  border_width_01: "1px",
  border_width_02: "2px",
  
  border_radius_01: "2px",
  border_radius_02: "4px",
  
  border_solid: "solid",
  border_none: "none",

**Comment by Lisa159** [comment]
Changes implemented in the branch advance-theme. They will be available in the next release. Closing issue.
