### ISSUE TITLE
[Slider] Add label and helper text

### ISSUE THREAD

**Issue by aweell** [dxc-technology/halstack-angular#456]
## Slider label and helper text

Changes on the specs can be found on: [Slider documentation draft](https://github.com/dxc-technology/halstack-style-guide/blob/component-slider/guidelines/components/slider/README.md)

![](https://github.com/dxc-technology/halstack-style-guide/raw/component-slider/guidelines/components/slider/images/slider_specs.png)

_Updated component specs_

- [ ] Add component label and helper text

Any fixes needed in the component documentation can be submitted to the [component review PR](https://github.com/dxc-technology/halstack-style-guide/pull/620)

**Comment by mawelCaballero** [comment]
I has been included on this PR: https://github.com/dxc-technology/halstack-angular/pull/471
Available in next version.
