### ISSUE TITLE
[Radio] Keyboard support

### ISSUE THREAD

**Issue by aweell** [dxc-technology/halstack-angular#470]
The focus between different options inside a radio group should be changed through keyboard arrows instead of `tab` key.

As a reference:

* [WAI-ARIA 1.2 - 3.18 Radio group design pattern](https://www.w3.org/TR/wai-aria-practices-1.2/#radiobutton)
* [WAI-ARIA 1.2 - Radio Group Example Using Roving tabindex](https://www.w3.org/TR/wai-aria-practices-1.2/examples/radio/radio.html)
* [WAI-ARIA 1.2 - 6.6 Keyboard Navigation Inside Components](https://www.w3.org/TR/wai-aria-practices-1.2/#kbd_general_within)

**Comment by jsardid** [comment]
Closing this one since we have a roadmap item here:
https://github.com/dxc-technology/halstack/issues/33
