### ISSUE TITLE
Text is not shown in Header

### ISSUE THREAD

**Issue by jsuarezgonz** [dxc-technology/halstack-angular#472]
**Describe the bug**
If you introduce a text component like p or h1 the text is not shown.

**To Reproduce**

1. Use DxcHeader.
2. Set in content prop: `<h1>hello</h1>.`
3. See error

**Expected behavior**
The text should be visible.

**Additional context**
Take as a reference the same issue that was solved in the React cdk. [issue#439](https://github.com/dxc-technology/halstack-react/issues/439)
In order to solve it, we will add contentColor and contentColorOnDark theme tokens that will apply to the custom (non-halstack) components used inside the header.

**Comment by Lisa159** [comment]
In Angular it is needed to use a container with specific id ('responsive' | 'unresponsive') to render content inside the Header component. (https://developer.dxc.com/tools/angular/next/#/components/header)

You can see it working here: https://stackblitz.com/edit/halstack-angular-examples?file=src%2Fapp%2Fviews%2Fheader%2Fdefault-header%2Fdefault-header.component.html
