### ISSUE TITLE
Pending Tasks for version 4

### ISSUE THREAD

**Issue by mawelCaballero** [dxc-technology/halstack-angular#479]
- [ ] Select: Define and create Form tests.
- [x] #525
- [x] #524
- [x] #502 
- [x] #490
- [x] #489
- [x] #480
- [x] #481
- [x] #458
- [x] #482
- [x] #483
- [x] #484
- [x] #485

- [x] Renaming duplicated components: 
   -  [x]  DxcNewInputText -> DxcTextInput
   -  [x]  DxcPassword -> DxcPasswordInput
   -  [x]  DxcNumber -> DxcNumberInput
   -  [x]  DxcNewDate -> DxcDateInput
   -  [x]  DxcNewTextarea -> DxcTextarea
   -  [x]  DxcNewSelect -> DxcSelect
   -  [x]  DxcInput -> DxcInputText
   -  [x]  DxcTextarea -> V3DxcTextarea
   -  [x]  DxcSelect -> V3DxcSelect
   -  [x]  Apply new Changes on app, doc, examples… etc.
   -  [x]  In doc site, autocomplete has to be missing and it has to be replaced by the autosuggest examples. 
   -  [x]  In previous input text component. Define an example oof autocomple.
  
- [x] #486
- [x] #487
- [x] #488
- [x] Create an inner component for doc site to define a components as deprecated. Tag deprecated. https://xd.adobe.com/view/668dbf0a-70e2-4ac4-b99e-1afba65efa43-33de/

   *Estilos Tag:*
```
   box-sizing: border-box;
    height: 24px;
    border: 1px solid #C59F07;
    border-radius: 0.5rem;
    padding: 4px 8px;
    font-size: 0.75rem;
    font-weight: 600;
    color: #624F04;
    background-color: #FFFDF5;
<a> sidenav:
a::before {
    display: table;
    content: "";
    margin-bottom: 0.21875rem;
a::after {
    display: table;
    content: "";
    margin-top: 0.21875rem;
Div sidenav:
    display: flex;
    align-items: center;
    gap: 0.5rem;
```

**Comment by Jialecl** [comment]
all completed in version 4 but "Select: Define and create Form tests." which won't be in the release 4.
